# Generated by Django 5.2.7 on 2025-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AddField(
            model_name='category',
            name='image_food',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
