# Generated by Django 5.2.7 on 2025-10-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_category_options_category_image_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
    ]
