# Generated by Django 5.2.7 on 2025-10-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
    ]
