# Generated by Django 5.2.7 on 2025-10-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_food', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m%d')),
                ('short_description', models.TextField(max_length=1000)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.menu')),
            ],
            options={
                'verbose_name_plural': 'item',
            },
        ),
    ]
