# Generated by Django 5.2.7 on 2025-10-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='item',
            new_name='item_p',
        ),
    ]
