# Generated by Django 5.2.7 on 2025-10-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_rename_item_make_item_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name_plural': 'item description'},
        ),
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
